services:
  youtube-transcript-api:
    build: .
    container_name: youtube-transcript-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    labels:
      # Enable Traefik
      - "traefik.enable=true"
      
      # HTTP Router
      - "traefik.http.routers.youtube-transcript.rule=Host(`youtube-transcript-api.martin-linde.com`)"
      - "traefik.http.routers.youtube-transcript.entrypoints=web"
      
      # HTTPS Router
      - "traefik.http.routers.youtube-transcript-secure.rule=Host(`youtube-transcript-api.martin-linde.com`)"
      - "traefik.http.routers.youtube-transcript-secure.entrypoints=websecure"
      - "traefik.http.routers.youtube-transcript-secure.tls=true"
      - "traefik.http.routers.youtube-transcript-secure.tls.certresolver=letsencrypt"
      
      # Middleware - Redirect HTTP to HTTPS
      - "traefik.http.middlewares.youtube-transcript-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.youtube-transcript-redirect.redirectscheme.permanent=true"
      - "traefik.http.routers.youtube-transcript.middlewares=youtube-transcript-redirect"
      
      # Service
      - "traefik.http.services.youtube-transcript.loadbalancer.server.port=8000"
    
    # Optional environment variables
    environment:
      - PORT=8000
